name: Test Python App

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Save requirements.txt as artifact
        run: |
          pip freeze > requirements.txt
          uses: actions/upload-artifact@v3
          with:
            name: requirements
            path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip freeze > requirements.txt
          pip install -r requirements.txt
          pip install fastapi
          pip install uvicorn
          pip install pydantic_settings
          pip install pytest httpx

      - name: Run tests
        run: python -m pytest "tests/"
