name: Test Python App

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies and create requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic_settings pytest httpx
          pip freeze > requirements.txt

      - name: Upload requirements.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: requirements
          path: requirements.txt

      - name: Run tests
        run: python -m pytest "tests/"
